# Based on https://github.com/robertdebock/ansible-role-openssh/blob/3ef8022bcc5a67f08262514f2ae754a537b40506/molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements_dev.yml
driver:
  name: docker
platforms:
  - name: "molecule-desktop_environment-${image:-ubuntu}-${tag:-latest}"
    image: "${image:-ubuntu}:${tag:-noble}"
ansible:
  playbooks:
    converge: converge.yml
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
